version: "3"

services:
 nodejs: 
   image: nodeauth
   container_name: node.js
   ports: 
   - "8080:8080" 
   environment: 
    PORT: 8080 
   links: 
   - bancomysql 
   depends_on: 
   - bancomysql 
 bancomysql:
  container_name: bancomysql 
  image: mysql:5.6.42
  ports:
      - "3606:3306"
  command: "--innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password"
  volumes:
    - ./dadosmysql:/var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodeauth
  restart: always
